# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "ehci_pci"
    "uas"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  #  fileSystems."/" =
  #    { device = "/dev/sda";
  #      fsType = "ext4";
  #    };

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/3151f42c-5ab3-4067-804b-bdb563f19e1a";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/36E8-C7B9";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  fileSystems."/backup" = {
    device = "/dev/disk/by-uuid/5fdb0575-4586-40cf-9715-33144cb92d57";
    fsType = "ext4";
    options = [
      "nofail"
      "x-systemd.idle-timeout=60"
    ];
  };

  fileSystems."/pool" = {
    device = "/dev/disk/by-uuid/4cc0e878-c863-4aef-bc33-5e7e92d85d9e";
    fsType = "ext4";
    options = [
      "nofail"
      "x-systemd.idle-timeout=60"
    ];
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/c555e750-506f-4c17-a76c-7438cc6599db"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
